### ISSUE TITLE
Failing lint

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-kafka#56] opened 2021-12-20 09:07 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The CI is failing due TypeScript linting

**Comment by Saber-Bjeoui** [comment] 2021-12-21 09:47
Hello @Eomm ,
I am trying to contribute here to resolve this issue.
Sorry if my question sound stupid am a newbie when it comes to CI,  but how are you doing CI here?

**Comment by Saber-Bjeoui** [comment] 2021-12-21 11:51
@Eomm After I did some checks I don't think the linter is the problem.
I did run `npx standard` and it exit with no errors !
But `npx tsd` gave the error that happend in the CI pipeline, this is the outout of `npx tsd`:
```
 node_modules/@fastify/ajv-compiler/index.d.ts:11:7
  ✖   11:0    Declaration or statement expected.                                                                                                             
  ✖   11:7    Cannot find name type.                                                                                                                         
  ✖   11:12   ; expected.                                                                                                                                    
  ✖   11:14   Ajv only refers to a type, but is being used as a value here.                                                                                  
  ✖   11:14   Left side of comma operator is unused and has no side effects.                                                                                 
  ✖   11:19   Options only refers to a type, but is being used as a value here.                                                                              
  ✖   11:29   Cannot find name from.                                                                                                                         
  ✖   11:34   ; expected.                                                                                                                                    

  node_modules/fastify/fastify.d.ts:11:9
  ✖   11:9    Module "../@fastify/ajv-compiler" has no exported member Options. Did you mean to use import Options from "../@fastify/ajv-compiler" instead?  
  ✖  179:0    Declaration or statement expected.                                                                                                             
  ✖  179:7    Cannot find name type.                                                                                                                         
  ✖  179:12   ; expected.                                                                                                                                    
  ✖  179:14   Cannot find name Chain.                                                                                                                        
  ✖  179:23   Cannot find name LightMyRequestChain.                                                                                                          
  ✖  179:44   Cannot find name InjectOptions.                                                                                                                
  ✖  179:59   Cannot find name Response.                                                                                                                     
  ✖  179:71   Cannot find name LightMyRequestResponse.                                                                                                       
  ✖  179:95   Cannot find name CallbackFunc.                                                                                                                 
  ✖  179:111  Cannot find name LightMyRequestCallback.                                                                                                       
  ✖  179:136  Cannot find name from.                                                                                                                         
  ✖  179:141  ; expected.                                                                                                                                    

  21 errors
```
It's weird that tsd includes files from node_modules when it shouldn't right?
I am still looking at what can be the cause and at the same time learning more about this lib and the deps used in it.
This is really a good first issue one.
Any guidance or suggestions will be appreciated.

**Comment by Eomm** [comment] 2021-12-22 09:51
> It's weird that tsd includes files from node_modules when it shouldn't right? 

Yeah, I agree.

I would just check the difference with another working repository:
https://github.com/fastify/fastify-mongodb/

I suspect the `tsd` version & configuration may impact on this behaviour

**Comment by Saber-Bjeoui** [comment] 2021-12-22 22:01
That's exactly what I did after I checked the installed 0.11 version where tsd is at 0.19 now!!
So after I upgraded tsd to version 0.19 which is the last version those errors above disappear and one new error popup!
but no node_modules errors. I don't know how much this upgrade will affect other parts of the code though I think some more changes need to be done to make this work.

**Comment by Saber-Bjeoui** [comment] 2021-12-22 22:11
Why packagelock.json is added to gitignore file?? is that on purpose?
I mean it should committed when changed, is there a reason for that?

according to [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion) this file need to be committed.

**Comment by kibertoad** [comment] 2021-12-23 00:49
@Saber-Bjeoui It should only be committed for user apps that actually get deployed. For frameworks and libraries package-lock does not bring any benefits.

**Comment by Saber-Bjeoui** [comment] 2021-12-23 19:32
@kibertoad ok I didn't know that, still learning how lib development is done.  Thanks for your answer anyway.

**Closed** 2022-01-11 15:41 UTC
Labels: good first issue
